### ISSUE TITLE
when to update SumerianConnector?

### ISSUE THREAD

**Issue by SXCC** [aws-samples/amazon-sumerian-arkit-starter-app#2]
I saw in the project that SumerianConnector was updated in delegate function "func renderer(_ renderer: SCNSceneRenderer, didApplyAnimationsAtTime time: TimeInterval)". May I ask why not update Connector in "func session(_ session: ARSession, didUpdate frame: ARFrame)"?

**Comment by mike-starr** [comment]
Good suggestion. I've updated SumerianConnector to work off the ARSessionDelegate's update method. Shouldn't be a significant difference in behavior, but the implementation is cleaner.
