### ISSUE TITLE
Microphone recording does not work on iOS

### ISSUE THREAD

**Issue by sam598** [aws-samples/amazon-sumerian-arkit-starter-app#3]
The application never requests microphone permissions, so the "Start Microphone Recording" and "Stop Microphone Recording" actions are never called, and audio can not be sent to the Amazon Lex chatbot.

**Comment by mike-starr** [comment]
Thanks for catching this - we'll investigate.

**Comment by suvratjain1995** [comment]
Hello @mike-starr , any update on this issue ?  as I am facing the same issue while creating an interactive experience with host.

**Comment by mike-starr** [comment]
This looks to be a result of the WebRTC APIs (specifically https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) not being available from the WKWebView class the sample app uses to host the Sumerian scene.

**Comment by aliang128** [comment]
> The application never requests microphone permissions, so the "Start Microphone Recording" and "Stop Microphone Recording" actions are never called, and audio can not be sent to the Amazon Lex chatbot.

same issue for me.

**Comment by mike-starr** [comment]
Just to close the loop on this, it's currently not possible to record via microphone using WKWebView. If that changes, I'll update this issue, but closing for now.

https://forums.developer.apple.com/thread/88052
http://www.openradar.me/33571214
