### ISSUE TITLE
Sumerian hosts do not load on mobile devices.

### ISSUE THREAD

**Issue by sam598** [aws-samples/amazon-sumerian-arkit-starter-app#4]
If a scene contains a host entity the AWS splash screen will appear, but never go away. The scenes will load in a desktop based browser. Other AR scenes will load fine within the app.

The same thing happens if a non AR scene with a host entity is opened in Safari or Chrome on iOS.

**Comment by mike-starr** [comment]
We're aware that hosts currently don't work properly on mobile Safari (or in the WKWebView used by this project). Will update this issue when we've resolved those problems.

**Comment by Reelevant** [comment]
Are any other scenes working? We were not able to load them on iOS browsers.

**Comment by mike-starr** [comment]
This has been fixed. Please re-publish your Sumerian scene to pick up the changes.
